export const technologyData= {
    language:[
        {
            image:'/images/technologyImages/javascript.svg',
            name:'javascript'
        },
        {
            image:'/images/technologyImages/typescript.svg',
            name:'typescript'
        },
    ],
    frontend:[
        {
            image:'/images/technologyImages/html5.png',
            name:'html'
        },
        {
            image:`/images/technologyImages/css3.svg`,
            name:'css'
        },
        {
            image:'/images/technologyImages/react.png',
            name:'react'
        },
        {
            image:'/images/technologyImages/styled-components.svg',
            name:'styled-components'
        },
        {
            image:'/images/technologyImages/bootstrap-logo.png',
            name:'bootstrap'
        },
        {
            image:'/images/technologyImages/sass-1.svg',
            name:'sass'
        },
    ],
    backend:[
        {
            image:'/images/technologyImages/node.svg',
            name:'nodeJs'
        },
        {
            image:'/images/technologyImages/express.svg',
            name:'ExpressJs'
        },
        {
            image:'/images/technologyImages/nestjs.svg',
            name:'NestJs'
        },
    ],
    database:[
        {
            image:'/images/technologyImages/mySql.svg',
            name:'mySql'
        },
        {
            image:'/images/technologyImages/mongodb.svg',
            name:'mongoDv'
        },
        {
            image:'images/technologyImages/typeorm.png',
            name:'typeOrm'
        },
        {
            image:'/images/technologyImages/prisma-2.svg',
            name:'prisma'
        },
    ]
}